/* Generated by erlresolvelinks at {{2015,3,31},{13,24,0}} UTC */
function erlhref(ups, app, rest) {
    switch(app) {
    case "doc/definitions":
        location.href=ups + "doc/definitions/" + rest;
        break;
    case "doc/design_principles":
        location.href=ups + "doc/design_principles/" + rest;
        break;
    case "doc/efficiency_guide":
        location.href=ups + "doc/efficiency_guide/" + rest;
        break;
    case "doc/embedded":
        location.href=ups + "doc/embedded/" + rest;
        break;
    case "doc/getting_started":
        location.href=ups + "doc/getting_started/" + rest;
        break;
    case "doc/html":
        location.href=ups + "doc/html/" + rest;
        break;
    case "doc/installation_guide":
        location.href=ups + "doc/installation_guide/" + rest;
        break;
    case "doc/oam":
        location.href=ups + "doc/oam/" + rest;
        break;
    case "doc/pdf":
        location.href=ups + "doc/pdf/" + rest;
        break;
    case "doc/programming_examples":
        location.href=ups + "doc/programming_examples/" + rest;
        break;
    case "doc/reference_manual":
        location.href=ups + "doc/reference_manual/" + rest;
        break;
    case "doc/system_architecture_intro":
        location.href=ups + "doc/system_architecture_intro/" + rest;
        break;
    case "doc/system_principles":
        location.href=ups + "doc/system_principles/" + rest;
        break;
    case "doc/top":
        location.href=ups + "doc/top/" + rest;
        break;
    case "doc/tutorial":
        location.href=ups + "doc/tutorial/" + rest;
        break;
    case "erts":
        location.href=ups + "/erts-6.4/doc/html/" + rest;
        break;
    case "asn1":
        location.href=ups + "lib/asn1-3.0.4/doc/html/" + rest;
        break;
    case "common_test":
        location.href=ups + "lib/common_test-1.10/doc/html/" + rest;
        break;
    case "compiler":
        location.href=ups + "lib/compiler-5.0.4/doc/html/" + rest;
        break;
    case "cosEvent":
        location.href=ups + "lib/cosEvent-2.1.15/doc/html/" + rest;
        break;
    case "cosEventDomain":
        location.href=ups + "lib/cosEventDomain-1.1.14/doc/html/" + rest;
        break;
    case "cosFileTransfer":
        location.href=ups + "lib/cosFileTransfer-1.1.16/doc/html/" + rest;
        break;
    case "cosNotification":
        location.href=ups + "lib/cosNotification-1.1.21/doc/html/" + rest;
        break;
    case "cosProperty":
        location.href=ups + "lib/cosProperty-1.1.17/doc/html/" + rest;
        break;
    case "cosTime":
        location.href=ups + "lib/cosTime-1.1.14/doc/html/" + rest;
        break;
    case "cosTransactions":
        location.href=ups + "lib/cosTransactions-1.2.14/doc/html/" + rest;
        break;
    case "crypto":
        location.href=ups + "lib/crypto-3.5/doc/html/" + rest;
        break;
    case "debugger":
        location.href=ups + "lib/debugger-4.0.3/doc/html/" + rest;
        break;
    case "dialyzer":
        location.href=ups + "lib/dialyzer-2.7.4/doc/html/" + rest;
        break;
    case "diameter":
        location.href=ups + "lib/diameter-1.9/doc/html/" + rest;
        break;
    case "edoc":
        location.href=ups + "lib/edoc-0.7.16/doc/html/" + rest;
        break;
    case "eldap":
        location.href=ups + "lib/eldap-1.1.1/doc/html/" + rest;
        break;
    case "erl_docgen":
        location.href=ups + "lib/erl_docgen-0.3.7/doc/html/" + rest;
        break;
    case "erl_interface":
        location.href=ups + "lib/erl_interface-3.7.20/doc/html/" + rest;
        break;
    case "et":
        location.href=ups + "lib/et-1.5/doc/html/" + rest;
        break;
    case "eunit":
        location.href=ups + "lib/eunit-2.2.9/doc/html/" + rest;
        break;
    case "gs":
        location.href=ups + "lib/gs-1.5.16/doc/html/" + rest;
        break;
    case "hipe":
        location.href=ups + "lib/hipe-3.11.3/doc/html/" + rest;
        break;
    case "ic":
        location.href=ups + "lib/ic-4.3.6/doc/html/" + rest;
        break;
    case "inets":
        location.href=ups + "lib/inets-5.10.6/doc/html/" + rest;
        break;
    case "jinterface":
        location.href=ups + "lib/jinterface-1.5.12/doc/html/" + rest;
        break;
    case "kernel":
        location.href=ups + "lib/kernel-3.2/doc/html/" + rest;
        break;
    case "megaco":
        location.href=ups + "lib/megaco-3.17.3/doc/html/" + rest;
        break;
    case "mnesia":
        location.href=ups + "lib/mnesia-4.12.5/doc/html/" + rest;
        break;
    case "observer":
        location.href=ups + "lib/observer-2.0.4/doc/html/" + rest;
        break;
    case "odbc":
        location.href=ups + "lib/odbc-2.10.22/doc/html/" + rest;
        break;
    case "orber":
        location.href=ups + "lib/orber-3.7.1/doc/html/" + rest;
        break;
    case "os_mon":
        location.href=ups + "lib/os_mon-2.3.1/doc/html/" + rest;
        break;
    case "ose":
        location.href=ups + "lib/ose-1.0.2/doc/html/" + rest;
        break;
    case "otp_mibs":
        location.href=ups + "lib/otp_mibs-1.0.10/doc/html/" + rest;
        break;
    case "parsetools":
        location.href=ups + "lib/parsetools-2.0.12/doc/html/" + rest;
        break;
    case "percept":
        location.href=ups + "lib/percept-0.8.10/doc/html/" + rest;
        break;
    case "public_key":
        location.href=ups + "lib/public_key-0.23/doc/html/" + rest;
        break;
    case "reltool":
        location.href=ups + "lib/reltool-0.6.6/doc/html/" + rest;
        break;
    case "runtime_tools":
        location.href=ups + "lib/runtime_tools-1.8.16/doc/html/" + rest;
        break;
    case "sasl":
        location.href=ups + "lib/sasl-2.4.1/doc/html/" + rest;
        break;
    case "snmp":
        location.href=ups + "lib/snmp-5.1.1/doc/html/" + rest;
        break;
    case "ssh":
        location.href=ups + "lib/ssh-3.2/doc/html/" + rest;
        break;
    case "ssl":
        location.href=ups + "lib/ssl-6.0/doc/html/" + rest;
        break;
    case "stdlib":
        location.href=ups + "lib/stdlib-2.4/doc/html/" + rest;
        break;
    case "syntax_tools":
        location.href=ups + "lib/syntax_tools-1.6.18/doc/html/" + rest;
        break;
    case "test_server":
        location.href=ups + "lib/test_server-3.8/doc/html/" + rest;
        break;
    case "tools":
        location.href=ups + "lib/tools-2.7.2/doc/html/" + rest;
        break;
    case "typer":
        location.href=ups + "lib/typer-0.9.8/doc/html/" + rest;
        break;
    case "webtool":
        location.href=ups + "lib/webtool-0.8.10/doc/html/" + rest;
        break;
    case "wx":
        location.href=ups + "lib/wx-1.3.3/doc/html/" + rest;
        break;
    case "xmerl":
        location.href=ups + "lib/xmerl-1.3.7/doc/html/" + rest;
        break;
    default:
        location.href=ups + "Unresolved";
    }
}
