/* Generated by erlresolvelinks at {{2021,5,31},{23,36,49}} UTC */
function erlhref(ups, app, rest) {
    switch(app) {
    case "doc/efficiency_guide":
        location.href=ups + "doc/efficiency_guide/" + rest;
        break;
    case "doc/getting_started":
        location.href=ups + "doc/getting_started/" + rest;
        break;
    case "doc/tutorial":
        location.href=ups + "doc/tutorial/" + rest;
        break;
    case "doc/installation_guide":
        location.href=ups + "doc/installation_guide/" + rest;
        break;
    case "doc/oam":
        location.href=ups + "doc/oam/" + rest;
        break;
    case "doc/xml":
        location.href=ups + "doc/xml/" + rest;
        break;
    case "doc/top":
        location.href=ups + "doc/top/" + rest;
        break;
    case "doc/system_architecture_intro":
        location.href=ups + "doc/system_architecture_intro/" + rest;
        break;
    case "doc/pdf":
        location.href=ups + "doc/pdf/" + rest;
        break;
    case "doc/design_principles":
        location.href=ups + "doc/design_principles/" + rest;
        break;
    case "doc/programming_examples":
        location.href=ups + "doc/programming_examples/" + rest;
        break;
    case "doc/definitions":
        location.href=ups + "doc/definitions/" + rest;
        break;
    case "doc/reference_manual":
        location.href=ups + "doc/reference_manual/" + rest;
        break;
    case "doc/embedded":
        location.href=ups + "doc/embedded/" + rest;
        break;
    case "doc/system_principles":
        location.href=ups + "doc/system_principles/" + rest;
        break;
    case "doc/html":
        location.href=ups + "doc/html/" + rest;
        break;
    case "erts":
        location.href=ups + "/erts-10.3.5.19/doc/html/" + rest;
        break;
    case "asn1":
        location.href=ups + "lib/asn1-5.0.8/doc/html/" + rest;
        break;
    case "common_test":
        location.href=ups + "lib/common_test-1.17.2.1/doc/html/" + rest;
        break;
    case "compiler":
        location.href=ups + "lib/compiler-7.3.2/doc/html/" + rest;
        break;
    case "crypto":
        location.href=ups + "lib/crypto-4.4.2.3/doc/html/" + rest;
        break;
    case "debugger":
        location.href=ups + "lib/debugger-4.2.6/doc/html/" + rest;
        break;
    case "dialyzer":
        location.href=ups + "lib/dialyzer-3.3.2/doc/html/" + rest;
        break;
    case "diameter":
        location.href=ups + "lib/diameter-2.2.1/doc/html/" + rest;
        break;
    case "edoc":
        location.href=ups + "lib/edoc-0.10/doc/html/" + rest;
        break;
    case "eldap":
        location.href=ups + "lib/eldap-1.2.7/doc/html/" + rest;
        break;
    case "erl_docgen":
        location.href=ups + "lib/erl_docgen-0.9/doc/html/" + rest;
        break;
    case "erl_interface":
        location.href=ups + "lib/erl_interface-3.11.3.2/doc/html/" + rest;
        break;
    case "et":
        location.href=ups + "lib/et-1.6.4/doc/html/" + rest;
        break;
    case "eunit":
        location.href=ups + "lib/eunit-2.3.7/doc/html/" + rest;
        break;
    case "ftp":
        location.href=ups + "lib/ftp-1.0.2.2/doc/html/" + rest;
        break;
    case "hipe":
        location.href=ups + "lib/hipe-3.18.3/doc/html/" + rest;
        break;
    case "inets":
        location.href=ups + "lib/inets-7.0.7.2/doc/html/" + rest;
        break;
    case "jinterface":
        location.href=ups + "lib/jinterface-1.9.1/doc/html/" + rest;
        break;
    case "kernel":
        location.href=ups + "lib/kernel-6.3.1.3/doc/html/" + rest;
        break;
    case "megaco":
        location.href=ups + "lib/megaco-3.18.4/doc/html/" + rest;
        break;
    case "mnesia":
        location.href=ups + "lib/mnesia-4.15.6/doc/html/" + rest;
        break;
    case "observer":
        location.href=ups + "lib/observer-2.9/doc/html/" + rest;
        break;
    case "odbc":
        location.href=ups + "lib/odbc-2.12.3/doc/html/" + rest;
        break;
    case "os_mon":
        location.href=ups + "lib/os_mon-2.4.7/doc/html/" + rest;
        break;
    case "otp_mibs":
        location.href=ups + "lib/otp_mibs-1.2.1/doc/html/" + rest;
        break;
    case "parsetools":
        location.href=ups + "lib/parsetools-2.1.8/doc/html/" + rest;
        break;
    case "public_key":
        location.href=ups + "lib/public_key-1.6.6.1/doc/html/" + rest;
        break;
    case "reltool":
        location.href=ups + "lib/reltool-0.7.8/doc/html/" + rest;
        break;
    case "runtime_tools":
        location.href=ups + "lib/runtime_tools-1.13.2.1/doc/html/" + rest;
        break;
    case "sasl":
        location.href=ups + "lib/sasl-3.3/doc/html/" + rest;
        break;
    case "snmp":
        location.href=ups + "lib/snmp-5.2.12/doc/html/" + rest;
        break;
    case "ssh":
        location.href=ups + "lib/ssh-4.7.6.6/doc/html/" + rest;
        break;
    case "ssl":
        location.href=ups + "lib/ssl-9.2.3.7/doc/html/" + rest;
        break;
    case "stdlib":
        location.href=ups + "lib/stdlib-3.8.2.4/doc/html/" + rest;
        break;
    case "syntax_tools":
        location.href=ups + "lib/syntax_tools-2.1.7.1/doc/html/" + rest;
        break;
    case "tftp":
        location.href=ups + "lib/tftp-1.0.1/doc/html/" + rest;
        break;
    case "tools":
        location.href=ups + "lib/tools-3.1.0.1/doc/html/" + rest;
        break;
    case "wx":
        location.href=ups + "lib/wx-1.8.7/doc/html/" + rest;
        break;
    case "xmerl":
        location.href=ups + "lib/xmerl-1.3.20.1/doc/html/" + rest;
        break;
    default:
        location.href=ups + "Unresolved";
    }
}
