#!/bin/bash

ROOT=${1}
BASEURL=${2}
HTML_PAGES=$(find "${ROOT}" -name "*.html" | sed "s|^${ROOT}/||" | grep -v notes.html | grep -v index.html | grep -v users_guide.html | grep -v release_notes.html)
DATE=$(date -Iseconds)

cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>

<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
EOF

for page in ${HTML_PAGES}; do
    case "${page}" in
        man/*)
            PRIORITY="0.7"
            ;;
        *)
            PRIORITY="0.5"
            ;;
    esac
    echo "   <url>
      <loc>${BASEURL}${page}</loc>
      <lastmod>${DATE}</lastmod>
      <changefreq>weekly</changefreq>
      <priority>${PRIORITY}</priority>
   </url>"
done

cat <<EOF
</urlset>
EOF
