#!/bin/bash

## Make sure to turn of From handling in settings/deploys#deploy-notifications

export

echo "Number of procs: $(nproc)"

git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.8.1
echo ". ~/.asdf/asdf.sh" >> ~/.profile

source "$HOME/.asdf/asdf.sh"

## We do not use asdf for ruby and node as neglify uses the correct one
asdf plugin add erlang
ERLC_USE_SERVER=true asdf install

## Install rebar3
mkdir ~/bin
curl https://s3.amazonaws.com/rebar3-nightly/rebar3 > ~/bin/rebar3
chmod +x ~/bin/rebar3
PATH=$PATH:$HOME/bin

## We set the BUNDLE_PATH to where netlify caches its gems
make -j $(nproc) build BUNDLE_PATH=/opt/build/cache/bundle

## Cleanup daemon processes
epmd -kill